Ask the OS/2 headers for DOS Semaphores
So that SEM_INDEFINITE_WAIT gets defined preventing errors like:
ckctel.c(787): Error! E1011: Symbol 'SEM_INDEFINITE_WAIT' has not been declared

In ckuath.c os2.h was only being included if CRYPT_DLL was defined even though the module uses definitions form there regardless. So now windows.h or os2.h is included always