Include types.h
So that fd_set will be declared fixing errors such as:
ckcftp.c(4728): Error! E1011: Symbol 'fd_set' has not been declared

For now this is ifdefd to Watcom - I've no idea if this file was broken for IBM compilers or if Watcom was just having issues here.